# Generated by Django 5.2.1 on 2025-05-16 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo_domain', models.CharField(default='', max_length=50)),
                ('todo_work', models.CharField(max_length=100)),
                ('todo_start', models.DateField()),
                ('todo_status', models.BooleanField()),
                ('todo_comment', models.CharField(default='', max_length=150)),
            ],
        ),
    ]
