# Generated by Django 5.2.1 on 2025-05-16 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='todo_start',
            new_name='todo_deadline',
        ),
    ]
